application: hew2017-iw13a627
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /(.*\.html)
  mime_type: text/html
  static_files: \1
  upload: (.*\.html)

- url: /css
  static_dir: css

- url: /img
  static_dir: img
  expiration: "5h"

- url: /js
  static_dir: js

- url: /pdf
  static_dir: pdf
  expiration: "5h"
